### ISSUE TITLE
为何安装fow失败？

### ISSUE THREAD

**Issue by luckypoem** [zhangxiaoyang/fow#1]
hi.

root@AR:/usr/local# npm install fow -g
npm ERR! Linux 2.6.32-042stab113.11
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "fow" "-g"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code EREADFILE

npm ERR! Error extracting /root/.npm/fow/0.0.4/package.tgz archive: ENOENT: no such file or directory, open '/root/.npm/fow/0.0.4/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/npm-debug.log
root@AR:/usr/local# fow -h
-bash: fow: 未找到命令
root@AR:/usr/local#

谢谢你

**Comment by zhangxiaoyang** [comment]
使用最新版本试试：https://nodejs.org/en/download/

**Comment by luckypoem** [comment]
hi.

root@AR:~# node --version
v5.3.0
root@AR:~#

不够新吗？

**Comment by zhangxiaoyang** [comment]
可以把log发一下吗？npm-debug.log

**Comment by luckypoem** [comment]
hi.

npm-debug.log内容为：
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'fow' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData fow
8 silly fetchNamedPackageData fow
9 silly mapToRegistry name fow
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/fow
13 verbose request uri https://registry.npmjs.org/fow
14 verbose request no auth needed
15 info attempt registry request try #1 at 00:55:39
16 verbose request id 16abca3a95c474da
17 verbose etag "AL19KE2FWF0JLMW261QYXHW55"
18 http request GET https://registry.npmjs.org/fow
19 http 304 https://registry.npmjs.org/fow
20 verbose headers { date: 'Fri, 26 Aug 2016 04:55:39 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"AL19KE2FWF0JLMW261QYXHW55"',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-ord1729-ORD',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1472187339.459623,VS0,VE340',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 304,
21 silly get   { date: 'Fri, 26 Aug 2016 04:55:39 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"AL19KE2FWF0JLMW261QYXHW55"',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-ord1729-ORD',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1472187339.459623,VS0,VE340',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose etag https://registry.npmjs.org/fow from cache
23 verbose get saving fow to /root/.npm/registry.npmjs.org/fow/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule fow@0.0.4 checking installable status
37 silly cache add args [ 'fow', null ]
38 verbose cache add spec fow
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'fow',
39 silly cache add   scope: null,
39 silly cache add   name: 'fow',
39 silly cache add   rawSpec: '',
39 silly cache add   spec: '_',
39 silly cache add   type: 'range' }
40 silly addNamed fow@_
41 verbose addNamed "_" is a valid semver range for fow
42 silly addNameRange { name: 'fow', range: '_', hasData: false }
43 silly mapToRegistry name fow
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry https://registry.npmjs.org/
46 silly mapToRegistry uri https://registry.npmjs.org/fow
47 verbose addNameRange registry:https://registry.npmjs.org/fow not in flight; fetching
48 verbose get https://registry.npmjs.org/fow not expired, no request
49 silly addNameRange number 2 { name: 'fow', range: '*', hasData: true }
50 silly addNameRange versions [ 'fow',
50 silly addNameRange   [ '0.0.3', '0.0.4', '0.0.5', '0.0.5-1', '0.0.5-2', '0.0.5-3' ] ]
51 silly addNamed fow@0.0.5
52 verbose addNamed "0.0.5" is a plain semver version for fow
53 silly cache afterAdd fow@0.0.5
54 verbose afterAdd /root/.npm/fow/0.0.5/package/package.json not in flight; writing
55 verbose afterAdd /root/.npm/fow/0.0.5/package/package.json written
56 silly rollbackFailedOptional Starting
57 silly rollbackFailedOptional Finishing
58 silly runTopLevelLifecycles Starting
59 silly runTopLevelLifecycles Finishing
60 silly install printInstalled
61 verbose stack Error: Error extracting /root/.npm/fow/0.0.4/package.tgz archive: ENOENT: no such file or directory, open '/root/.npm/fow/0.0.4/package.tgz'
61 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:286:10)
61 verbose stack     at emitOne (events.js:77:13)
61 verbose stack     at ReadStream.emit (events.js:169:7)
61 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:179:14
61 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:16
61 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
62 verbose cwd /usr/local
63 error Linux 2.6.32-042stab113.11
64 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "fow"
65 error node v5.3.0
66 error npm  v3.3.12
67 error code EREADFILE
68 error Error extracting /root/.npm/fow/0.0.4/package.tgz archive: ENOENT: no such file or directory, open '/root/.npm/fow/0.0.4/package.tgz'
69 error If you need help, you may report this error at:
69 error     https://github.com/npm/npm/issues
70 verbose exit [ 1, true ]

**Comment by zhangxiaoyang** [comment]
npm install fow@0.0.5-3
试试呢

**Comment by luckypoem** [comment]
HI.

安装成功了.谢谢你

**Comment by luckypoem** [comment]
不过，不能分页吗

**Comment by zhangxiaoyang** [comment]
考虑到持续写作是很难的，所以没有加这个功能~欢迎提交代码哈。
